### ISSUE TITLE
hasSwears to return boolean instead using callback

### ISSUE THREAD

**Issue by JuhQ** [gmemstr/no-swears#2]
I think `hasSwears` method should return boolean instead of calling an callback function.
With the way this library is currently built, it's impossible to write line like this:

```
if (hasSwears(words)) { ... }
```

Or use filter/map/etc like this

```
something()
  .filter(hasSwears)
```

**Comment by gmemstr** [comment]
The underlying issue of this is that I'm using the async version of `fs.readFile`. I'll probably implement non-async methods in the end, but trying to see what I can do now.

**Comment by JuhQ** [comment]
https://nodejs.org/api/fs.html#fs_fs_readfilesync_path_options

 - Juha

**Comment by gmemstr** [comment]
Added `hasSwearsSync()` method which returns bool.
